### ISSUE TITLE
Muon Cross Section Use Muon Mass

### ISSUE THREAD

**Issue by tomeichlersmith** [tomeichlersmith/ldmx-sim-technique#5]
Currently, SimCore just uses the electron mass everywhere the lepton mass is needed in the cross section calculation. It should be an easy fix to patch it up so that it uses the correct mass depending on which lepton is being used.

**Comment by revering** [comment]
We need to be careful which electron masses get switched in the cross section calculation, as some of them correspond to the incident lepton mass and should change, while some are from the atomic screening terms and should remain as the electron mass. The ones that I think should change can be seen in my implementation of the muon process:
https://github.com/revering/cmssw/blob/3879b623807fc9bd315086128f74e6c21153b0a2/SimG4Core/CustomPhysics/src/G4muDarkBremsstrahlungModel.cc#L267
This setup sees _ok_ agreement with madgraph, though the madgraph result was also created by me changing the same parameters, so some discussion with theorists will be useful.
