### ISSUE TITLE
Use atomic number instead of atomic mass when calling cross section per atom

### ISSUE THREAD

**Issue by revering** [tomeichlersmith/ldmx-sim-technique#8]
One of the CMSSW reviewers noticed that I used (*theElementVector)[i]->GetA() instead of   (*theElementVector)[i]->GetN() when calling the cross section per atom while building the per-material table that CMSSW uses to pick which element initiated the process. ComputeCrossSectionPerAtom actually needs the number of nucleons, not the atomic mass.
The line
https://github.com/tomeichlersmith/ldmx-sim-technique/blob/2d86cce3c06eb914e3a5cc52ea4c8a5bdac54d45/sim/sw/G4DarkBreM/src/G4DarkBreM/G4DarkBremsstrahlung.cxx#L200
should accordingly use GetN() instead of GetA() / (g/mol). 

I don't have an exact sense offhand how much this changes the cross section - I'll check when I get back into the office on Monday. It shouldn't change any of our plots, but if you use this simulation for any total rate predictions the cross section will change. Fortunately I used the default GetMeanFreePath with the CMSSW one so only the element picking is changed, but in this implementation it could have a significant impact. All of the cross section comparisons used in the paper call the computation directly, and are not impacted.

I think there are a few other locations that need this update as well (like wherever the element xsec cache gets built).

**Comment by revering** [comment]
I just now remembered my basic physics and that the atomic mass is extremely close to the number of nucleons. The choice between GetA() / (g / mole) and GetN() should make essentially no difference. Technically any built-in geant function that calls CalculateCrossSectionPerAtom will use GetN(), but it really shouldn't change anything. I'm guessing they are making me change the CMSSW one just for better consistency across process implementations.

**Comment by tomeichlersmith** [comment]
Thanks for the update from the CMSSW folks! To me, it's comforting to know we are talking about low-level, small-effect things since that (probably) means the big stuff is all good! :)
